version: '3.2'

services:
  rover_database:
    image: postgres:9.6-alpine
    container_name: rover_database
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"

  rover:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'" 
    container_name: rover 
    stdin_open: true
    tty: true
    volumes:
      - .:/rover
    ports:
      - "3000:3000"
    depends_on:
      - rover_database

volumes:
  pg_data:
